### ISSUE TITLE
Provide `FREE` service (together with current `XE`)

### ISSUE THREAD

**Issue by mvorisek** [gvenzl/oci-oracle-xe#238]
To allow easier migration to https://github.com/gvenzl/oci-oracle-free/issues, especially to test both in CI, please provide together with the current `XE` service also `FREE`, so the image name is enough to parametrize the database version.

**Comment by gvenzl** [comment]
Hey @mvorisek,

Thanks for this excellent idea, I like it!
This will indeed make the migration to the new Oracle Database Free much easier going forward.

Will work on it.

**Comment by gvenzl** [comment]
Fixed and will release this weekend.

**Comment by mvorisek** [comment]
In doctrine/dbal project the following easy connect string `(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SID=FREE)))` is still not working with v<23. `localhost/free` works however. Any idea, is SID emulated well enough?

**Comment by mvorisek** [comment]
@gvenzl can I please ask you to look into this issue related with https://github.com/gvenzl/oci-oracle-xe/commit/77a2e80758f4c37be97c5599f3775226dc664cae?

**Comment by mprins** [comment]
changing the JDBC url from:
`jdbc:oracle:thin:@localhost:15210:FREE`
to
`jdbc:oracle:thin:@localhost:15210/FREE`
fixed things for me as it now connects to the service and not the SID

**Comment by mvorisek** [comment]
Thank you, you identified the problem - we need to provide `FREE` SID instead of only `FREE` service name! Would you be able to send a PR to improve https://github.com/gvenzl/oci-oracle-xe/commit/0cedd27ab04771789f1425639434d33940935f6c to provide also `FREE` SID?

**Comment by gvenzl** [comment]
Hey @mvorisek,

The ORACLE_SID for Oracle XE cannot be changed, it's fixed to `XE` (just like for Oracle Free it's fixed to `FREE`). So you will have to connect via the service name if you want to use `FREE`.
